# Generated by Django 5.2.14 on 2026-05-11 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["model", "manufacturer", "manufacturer__country"]},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ["name"]},
        ),
    ]
