# Generated by Django 5.2.14 on 2026-05-11 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_alter_car_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["manufacturer", "manufacturer__country"]},
        ),
    ]
